/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InvoiceSummaryPane.java
 *
 * Created on 24-jul-2010, 12:29:18
 */
package facturasapp;

import facturasapp.data.DataManager;
import facturasapp.data.FileManager;
import facturasapp.data.HTMLManager;
import facturasapp.data.StoreManager;
import facturasapp.events.FacturaAdapter;
import facturasapp.events.FacturaEvent;
import facturasapp.events.EventManager;
import facturasapp.events.FacturaListener;
import facturasapp.events.SearchAdapter;
import facturasapp.events.SearchEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.jdo.JDOHelper;
import javax.jdo.PersistenceManager;
import javax.jdo.PersistenceManagerFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import storeDataModel.Invoice;
import storeDataModel.ProductRelation;

/**
 *
 * @author CiberXtrem
 */
public class SearchSummaryPane extends javax.swing.JPanel {

    /** Creates new form InvoiceSummaryPane */
    public SearchSummaryPane() {
        initComponents();
        initCustomComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseImpLabel = new javax.swing.JLabel();
        totalImporteField = new javax.swing.JTextField();
        porcentajeIvaLabel = new javax.swing.JLabel();
        porcentIvaField = new javax.swing.JTextField();
        ImpIvaLabel = new javax.swing.JLabel();
        impIvaField = new javax.swing.JTextField();
        totalFactLabel = new javax.swing.JLabel();
        totalFactField = new javax.swing.JTextField();
        GuardarButton = new javax.swing.JButton();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(facturasapp.FacturasApp.class).getContext().getResourceMap(SearchSummaryPane.class);
        baseImpLabel.setFont(resourceMap.getFont("baseImpLabel.font")); // NOI18N
        baseImpLabel.setText(resourceMap.getString("baseImpLabel.text")); // NOI18N
        baseImpLabel.setName("baseImpLabel"); // NOI18N

        totalImporteField.setText(resourceMap.getString("totalImporteField.text")); // NOI18N
        totalImporteField.setName("totalImporteField"); // NOI18N

        porcentajeIvaLabel.setFont(resourceMap.getFont("porcentajeIvaLabel.font")); // NOI18N
        porcentajeIvaLabel.setText(resourceMap.getString("porcentajeIvaLabel.text")); // NOI18N
        porcentajeIvaLabel.setName("porcentajeIvaLabel"); // NOI18N

        porcentIvaField.setText(resourceMap.getString("porcentIvaField.text")); // NOI18N
        porcentIvaField.setName("porcentIvaField"); // NOI18N
        porcentIvaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentIvaFieldActionPerformed(evt);
            }
        });

        ImpIvaLabel.setFont(resourceMap.getFont("ImpIvaLabel.font")); // NOI18N
        ImpIvaLabel.setText(resourceMap.getString("ImpIvaLabel.text")); // NOI18N
        ImpIvaLabel.setName("ImpIvaLabel"); // NOI18N

        impIvaField.setText(resourceMap.getString("impIvaField.text")); // NOI18N
        impIvaField.setName("impIvaField"); // NOI18N

        totalFactLabel.setFont(resourceMap.getFont("totalFactLabel.font")); // NOI18N
        totalFactLabel.setText(resourceMap.getString("totalFactLabel.text")); // NOI18N
        totalFactLabel.setName("totalFactLabel"); // NOI18N

        totalFactField.setText(resourceMap.getString("totalFactField.text")); // NOI18N
        totalFactField.setName("totalFactField"); // NOI18N

        GuardarButton.setIcon(resourceMap.getIcon("GuardarButton.icon")); // NOI18N
        GuardarButton.setText(resourceMap.getString("GuardarButton.text")); // NOI18N
        GuardarButton.setName("GuardarButton"); // NOI18N
        GuardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(baseImpLabel)
                    .addComponent(totalImporteField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(porcentajeIvaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcentIvaField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImpIvaLabel)
                    .addComponent(impIvaField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalFactField)
                    .addComponent(totalFactLabel))
                .addGap(18, 18, 18)
                .addComponent(GuardarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GuardarButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ImpIvaLabel)
                                .addComponent(totalFactLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(totalFactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(impIvaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(porcentajeIvaLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(porcentIvaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(baseImpLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(totalImporteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarButtonActionPerformed
        if(invoice !=null){
        //Save HTML file & Pring history
                        //Pring history
            try {
                HTMLManager.generateHistory(invoice, "history\\" + invoice.getId() + ".html");
            } catch (IOException ex) {
                Logger.getLogger(InvoiceSummaryPane.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_GuardarButtonActionPerformed

    private void porcentIvaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentIvaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_porcentIvaFieldActionPerformed

    public void initCustomComponents() {

        //Listener
        EventManager.getInstance().addSearchListener(new SearchAdapter() {

            @Override
            public void invoiceSelected(SearchEvent e) {
                //Hacer resumen
                invoice = (Invoice) e.getSource();
                 totalImporteField.setText(String.valueOf(invoice.getBaseImponible()));
                porcentIvaField.setText(String.valueOf(invoice.getIva()*100));
                impIvaField.setText(String.valueOf(invoice.getImporteIva()));
                totalFactField.setText(String.valueOf(invoice.getTotal()));
            }

            @Override
            public void invoiceUnselected(SearchEvent e){
                invoice = null;
                totalImporteField.setText("");
                impIvaField.setText("");
                totalFactField.setText("");
                porcentIvaField.setText("");
            }

            @Override
            public void newSearch (SearchEvent e){
                //Reset when starting a newSearch
                invoice = null;
                totalImporteField.setText("");
                impIvaField.setText("");
                totalFactField.setText("");
                porcentIvaField.setText("");
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarButton;
    private javax.swing.JLabel ImpIvaLabel;
    private javax.swing.JLabel baseImpLabel;
    private javax.swing.JTextField impIvaField;
    private javax.swing.JTextField porcentIvaField;
    private javax.swing.JLabel porcentajeIvaLabel;
    private javax.swing.JTextField totalFactField;
    private javax.swing.JLabel totalFactLabel;
    private javax.swing.JTextField totalImporteField;
    // End of variables declaration//GEN-END:variables
    //Custom Variables
    Invoice invoice = null;
    //End Custom Variables
}
