/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InvoicePane.java
 *
 * Created on 24-jul-2010, 12:32:07
 */

package facturasapp;

import facturasapp.data.DataManager;
import facturasapp.events.EventManager;
import facturasapp.events.SearchAdapter;
import facturasapp.events.SearchEvent;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import storeDataModel.Invoice;
import sun.awt.VerticalBagLayout;

/**
 *
 * @author CiberXtrem
 */
public class SearchPane extends javax.swing.JPanel {

    /** Creates new form InvoicePane */
    public SearchPane() {
        //initComponents();
        initCustomComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
 public void initCustomComponents(){
     //this.setLayout(new GridLayout(4,0));
     GridLayout grid = new GridLayout();
     grid.setColumns(1);
     grid.setRows(4);
     grid.setVgap(1);
     //this.setLayout(grid);
     this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));

     this.add(searchStartPane);
     this.add(searchPreviewPane);
     this.add(searchShoppingCartPane);
     this.add(searchSummaryPane);

      EventManager.getInstance().addSearchListener(new SearchAdapter() {
            public void newSearch(SearchEvent e) {
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    //Custom Variables
    SearchStartPane searchStartPane = new SearchStartPane();
    SearchPreviewPane searchPreviewPane = new SearchPreviewPane();
    SearchShoppingCartPane searchShoppingCartPane = new SearchShoppingCartPane();
    SearchSummaryPane searchSummaryPane = new SearchSummaryPane();
    //End Custom Variables

    //Data Custom Variables

    //End Data Custom variables
}
